name: Maven CI

# Triggers manually or on push or pull request on the main branch
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  # Runs the Maven test phase on the project
  maven_test:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    # The uses: keyword invokes a GitHub action:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # This invokes the Setup Java JDK GitHub action:
    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

    # Cache the build files to speed up subsequent runs
    - name: Cache build
      uses: actions/cache@v3
      with:
        key: cached-build-${{github.sha}}
        path: .

    - name: Test with Maven
      run: mvn test

    # Upload JaCoCo coverage results as an artifact
    - name: Upload jacoco results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Jacoco coverage results
        path: target/site/jacoco

  # Uploads dependency graph to GitHub to receive Dependabot alerts 
  update_dependence_graph:

    # Ensures that this job waits for maven_test to complete
    needs: [maven_test]

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    # Restore the cached build files
    - name: Restore cached build
      uses: actions/cache@v3
      with:
        key: cached-build-${{github.sha}}
        path: .

    # Update the dependency graph
    # https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
